---
- name: Setup Minecraft Server
  hosts: minecraft
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Add OpenJDK PPA
      apt_repository:
        repo: ppa:openjdk-r/ppa
        state: present

    - name: Download OpenJDK 21 from Adoptium
      get_url:
        url: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1+12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
        dest: /tmp/openjdk-21.tar.gz

    - name: Extract OpenJDK 21
      unarchive:
        src: /tmp/openjdk-21.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Set JAVA_HOME and add to PATH
      copy:
        dest: /etc/profile.d/jdk21.sh
        content: |
          export JAVA_HOME=/opt/jdk-21.0.1+12
          export PATH=$JAVA_HOME/bin:$PATH
        mode: "0755"

    - name: Create minecraft directory
      file:
        path: /home/ubuntu/minecraft
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy server.jar to instance
      copy:
        src: files/server.jar
        dest: /home/ubuntu/minecraft/server.jar
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Accept Minecraft EULA
      copy:
        src: files/eula.txt
        dest: /home/ubuntu/minecraft/eula.txt
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/minecraft
          ExecStart=/opt/jdk-21.0.1+12/bin/java -Xmx2G -Xms1G -jar server.jar nogui
          ExecStop=/bin/kill -SIGINT $MAINPID
          Restart=always
          KillMode=none
          SuccessExitStatus=0 1

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Enable and start Minecraft

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start Minecraft
      systemd:
        name: minecraft
        enabled: yes
        state: started
